name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia 'main' si tu rama principal se llama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Comandos que se ejecutarán en la instancia EC2
            sudo apt update -y
            sudo apt install apache2 php libapache2-mod-php git -y

            # Eliminar el contenido predeterminado
            sudo rm -rf /var/www/html/*

            # Clonar tu repositorio
            cd /var/www/html
            git clone https://github.com/Macedux/AP5.git .  # Reemplaza esto si es necesario

            # Cambiar los permisos del directorio
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Reinicia el servicio de Apache
            sudo systemctl restart apache2
          EOF

