name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal se llama diferente

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t myapp .  # Reemplaza myapp con el nombre que desees para tu imagen

      - name: Push Docker image to Docker Hub
        run: |
          docker tag myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest  # Cambia myapp si es necesario
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Pull the Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest

            # Stop and remove any running container (if any)
            docker stop myapp || true
            docker rm myapp || true

            # Run the new container
            docker run -d --name myapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          EOF
